### PR TITLE
Reference code from GitHub

### PR DESCRIPTION
**Pull request by YOU54F**
Hey @duanwilliam,

Nice project!

I wanted created some multi code tabs, driven by data objects, that could be stored locally but also retrieved from source code. I've built a component to do it now and in the processing of packaging up, but came across your project which is really nice.

I think I am going to incorporate bits of it into mine.

Anyway, I found a project that was sourcing GH code from an URL and creating a code block 

https://github.com/saucelabs/docusaurus-theme-github-codeblock

However it wasn't working out the box, so I had to tweak it, but I really liked the example code link they provide, so I added it to this project. I also added some tests as well 👍🏾 

Here is my site that I am building some docs and examples against, https://docusaurus-tab-generator.vercel.app/ 

Any way, I made some tweaks in a fork of https://github.com/saucelabs/docusaurus-theme-github-codeblock so that you can provide some fallback text, if the call for GH fails for whatever reason, it works really nicely with your project

## Display multiple code in tabs, from Markdown

- `codeLocation="https://foo.com"` - renders a `See full example on GitHub link`
- `title="example"` - renders a custom title
- Add a GitHub `URL` on the 1st line, to render a code block from GitHub

### code

    ```md codetabs

    ```js title="index.js" codeLocation="https://foo.com"
    const main = () => {
      console.log("Hello, world");
    }

    ```rust title='main.rs'
    let assignTitle: &str = r#"title="main.rs""#;

    ```cpp reference title="main.cpp"
    https://github.com/saucelabs/docusaurus-theme-github-codeblock/blob/main/src/theme/ReferenceCodeBlock/index.tsx#L105-L108
    #include <iostream>
    using namespace std;
    int main() {
      cout << "Hello, world" << endl;
    }

    ```cpp label="C++11" title="main.cpp"
    string label="C++11";

        ```
    this is an important comment.

    ```jsx title="Component.jsx"
    <Tabs>
      <TabItem />
      <TabItem />
    </Tabs>
        ```
    ```

![Screenshot 2022-04-11 at 00 24 56](https://user-images.githubusercontent.com/19932401/162644375-d1fd99fd-d1e7-4e19-a57d-4aad7df8879e.png)

![Screenshot 2022-04-11 at 00 24 49](https://user-images.githubusercontent.com/19932401/162644355-078a55e4-a85c-4709-bee0-41cb283c3826.png)

![Screenshot 2022-04-11 at 00 25 05](https://user-images.githubusercontent.com/19932401/162644380-5ac1cb4c-8950-4f19-9c0f-b65f8e10085c.png)

### CODE REVIEW

**Comment by duanwilliam** [comment]
Ideally this plugin should work fine with other Remark plugins that operate on code blocks, or end consumers that use the CodeBlock component, as this plugin should just unwrap the special `codetabs` syntax into Docusaurus tabs with code blocks in each individual tab.

Could you elaborate on how this plugin failed to work with that Docusaurus theme plugin (i.e. how it wasn't working out of the box,? I'd rather just fix this plugin to properly interact with other plugins than add extraneous functionality.

**Comment by YOU54F** [comment]
Hey,

So your plugin works perfectly.

I was trying to use it with https://github.com/saucelabs/docusaurus-theme-github-codeblock

The linked project doesn't work out the box because of the 1st issue, and isn't ideal because of the 2nd

- cannot resolve url module - [here](https://github.com/saucelabs/docusaurus-theme-github-codeblock/issues/18)
- unwanted re-renders in react - [here](https://github.com/saucelabs/docusaurus-theme-github-codeblock/issues/9)

I also added the ability to have fallback text, if the GitHub code source fails [here](https://github.com/saucelabs/docusaurus-theme-github-codeblock/pull/21).

My changes for your project are

- Allow an optional example location text/link section to be rendered after the codetabs block if a param is set `codeLocation` at the moment. It is as per this code is the aforementioned [plugin](https://github.com/saucelabs/docusaurus-theme-github-codeblock/blob/3e94f0555f93f97fbb4db46673905dc6b9fe1635/src/theme/ReferenceCodeBlock/index.tsx#L129)
- Add some tests

My motivation is 

- we have an OSS project in 14+ implementations, I want to showcase our features, and currently stored in markdown, we have ruby examples only. We have GitHub code in the other languages we can pull in. example here https://docs.pact.io/getting_started/matching#regular-expressions

Here was my first attempt at using it stored in markdown (before I found both plugins https://docs.pactflow.io/#pact-js-node-js)

So I would like to make codemd tabs, some sourced from GH, some sourced locally (as per your project)

I want to make the UI consistent, so in each code tab, I can show an example link to code, regardless of whether it was sourced from GH, via the linked plugin, or generated by codemd and shown locally

Hope that helps provide some more context

**Comment by duanwilliam** [comment]
Again, I don't wish to add extraneous functionalities when other plugins can handle that; I do agree that it could be useful to be able to add other content to the tab, though. I've opened an issue about it at #2

**Comment by YOU54F** [comment]
No problem Duan! I appreciate you taking the time to view, and your proposal looks very well thought out.

I think for my use case however, due to the scope caveat I will just continue with my plugin to serve my needs. Thanks again!

**Pull request closed without merging**
